Bug fix - Latest React version causes Uncaught TypeError
Error thrown using React 15: Uncaught TypeError: _react2.default.render is not a function

* Add react-dom dependency in package.json

* Add latest react to dependencies in package.json

* Change React.render to ReactDOM.render in app.js

* Update README.md